env:
  es2022: true
  node: true
extends:
  - standard
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules: {}
globals:
  it: true
  test: true
  jest: true
  expect: true
  describe: true
  beforeAll: true
  afterAll: true
  beforeEach: true
  afterEach: true